sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs-v2
  - '0.12'
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
script: TEST_CLIENT=selenium:firefox npm test
after_success:
  - npm run semantic-release
