sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  # re-enab le iojs when https://github.com/pouchdb/pouchdb/pull/4236 is resolved
  # - iojs-v2
  - '0.12'
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
script: TEST_CLIENT=selenium:firefox npm test
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run semantic-release
