language: node_js
node_js:
- '0.10'
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
before_install:
- npm i -g npm@^2.0.0
# See https://github.com/boennemann/semantic-release/issues/18
before_deploy:
- npm config set spin false --global
env:
  global:
  - secure: "A24dfI7oJyeqX6bxrOumTsWw9835rMwYly71iC6Lo0907WuTNNDAD7ZopXlLhagFGjJqXyPyR5S+u3rTsELcXyfDaAU23rzU41DpCv/3OgUoN/eM0Q6Nh7bWbgBrCWS6CovhTFBcHI3FOkxP00oPS16A/+zIzxk2EHtV6ksFGwxLx5llSgudVjP4R57M92/sVpa39Vmyn2iUm/Yd1LHH0t4t57XMLB+IwZXhe2XuqfmEeIzTdEOhptPHVBLpP0fIr+Cr7yQqDKD8+Xji5uKv7WeIXaz+EfCFwiCrqO4m1p5F5hMi+7tVL3A3cjMiGlg5/SNqfE8S6IQUP2JPFNc1QjN5MV2tUKLnC9+ZPkII+G59U5ERRz8w5bHYgT2s+Su9HTWywGmapOvxk4tNzKX26wbLavgGkRSag3NCOo1QoP+Ht8CNFK017XqGPyuhd7McEhPRTV8w9uwjuN0Di4mXUy5ELKz94QWApJRa7+fIHJvyIdEh9i9EUfF4oQ35l/UFhdewO3mmkjEvs6ZEn8fiBPkxEermOul8GFbs5htQUMHHF72yLfeOdXRhnPcefFyTXgdpoECQgWpOnHh2LVKsxVlbKVDYu0M6uQx8WNhi69e+wqxbtASLGP4DkcqCBGmCpEuTc8RiuLlM9Ep03plbY9OYXbnkDCxKbL4x7coJFnA="
deploy:
  provider: npm
  email: gregor@martynus.net
  skip_cleanup: true
  api_key:
  - secure: "cBCwzmUx+GICt9gvQxQOk4iCl2qGV3STxsNcmzNC73/jTJwCQKzMrZft12cWcWtB8N0SgdqSuArMmZcUq7tmOg9vzWiJedKKz40uQFvnKVBpxdUtf7GSvEaXhSgLJR80tZ/dUCPGEX40hCGOOqvrrzL7MmuD/65GMmEXPiJmERbOMx1R4Fa3rhGnjq4MeDWZnwg2GfNMbg8ZIGnhnWy2geDLJPiH25HIYsdntdJMjhfZHXCLRYjrsAVddSo0qcqWkiDyRaFWo8S1oMepqwAUvSwHkNx0r27SDpQU5ZUF7PobWWLG05kTiJq5wCafZD195otn0QosrJGIync9csva531vyXDeIpYOIkOMqxCqo//JQd6V5EJgYp/ok8gMndSz1iYA8DvfWV53LYCXk3cbuRQtUcw/zFIirfgiZ4AywXIql96h2WPz69CUMMA/u8KY00b1x9fLzBkGc45ETpHisounVgUuqY/68AXqWk2iAUAZ9bE+L14IBrFjZoaUoY+5w2AD12kPnvHCnNhu5Bs1mEH5Ly+C+1ou7rw2hLJW5XH9Lbd3ByQdUmgTYWzmfWMGl3vUmcGBJJ1exnB0jH4NiHABrxsUo8Xv26KcLLtSKUjye3EdtTOk/3trGiWG99JVZ49BGEZB4U97Am9L6Kmk+LL6n3ocMk9Yt1EuPdjvgjs="
  on:
    branch: master
    repo: eHealthAfrica/kazana
